window.MALL_FOOD_PICKER = {
  "config": {
    "site_name": "SEACON BANGKAE FOOD PICKER",
    "mall_name": "ซีคอน บางแค · กรุงเทพมหานคร",
    "kicker": "SEACON BANGKAE DINING DIRECTORY",
    "headline": "มื้อนี้ กินอะไรดี?",
    "description": "ค้นหาร้านตามชั้น หมวดหมู่ และโซน หรือให้วงล้อช่วยเลือกมื้อนี้แทนคุณ",
    "primary_color": "#25316d",
    "accent_color": "#ffdc34",
    "highlight_color": "#e64072",
    "language": "th",
    "source_note": "อัปเดตข้อมูล 21 ก.ย. 2569 จาก Punpro, Shop Directory ของ Seacon Bangkae, Google Maps และช่องทางทางการของร้าน โปรดตรวจสอบเวลาเปิดก่อนเดินทาง",
    "homepage_url": "https://thanakritdacontact-tech.github.io/seacon-bangkae-food-picker/"
  },
  "restaurants": [
    {
      "id": "1-2-coffee-company-bd99c38a",
      "name": "1 : 2 Coffee Company",
      "category": "เครื่องดื่มและคาเฟ่",
      "location": "อาคารหลัก",
      "floor": "1",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=1%20%3A%202%20Coffee%20Company%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmG9z69IHKEXL0OOhB3lewzqfbNpsqW1OSRV-u0ppnQm0tTJXG8fZoL5KI9AgsV8CC7KXvft_QBqIUfpTSwxYFlxGCEN75dh-3lJvW654xbihWeumNjzWUv_3qYkigd6YtqT2itsQ=w408-h306-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=1%20%3A%202%20Coffee%20Company%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "shop-379183e4",
      "name": "ชาตรามือ",
      "category": "เครื่องดื่มและคาเฟ่",
      "location": "อาคารหลัก",
      "floor": "1",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=%E0%B8%8A%E0%B8%B2%E0%B8%95%E0%B8%A3%E0%B8%B2%E0%B8%A1%E0%B8%B7%E0%B8%AD%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlZ0ftpYmS6OpaLsHbeun4N_gLFf41vMSXR1stpRxrBDIRg7bpzEXFh8jo-otvRx5W3tnPw8GzWrzoC4giycjsDgJKjXQ4xaJ4QTnHcPy-2jfX4u12xNnweFtzwhrt21LcaC6r_=w408-h544-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=%E0%B8%8A%E0%B8%B2%E0%B8%95%E0%B8%A3%E0%B8%B2%E0%B8%A1%E0%B8%B7%E0%B8%AD%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "shop-85ae5218",
      "name": "สุกี้ตี๋น้อย",
      "category": "ชาบูและสุกี้",
      "location": "หน้าศูนย์การค้า",
      "floor": "1",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=%E0%B8%AA%E0%B8%B8%E0%B8%81%E0%B8%B5%E0%B9%89%E0%B8%95%E0%B8%B5%E0%B9%8B%E0%B8%99%E0%B9%89%E0%B8%AD%E0%B8%A2%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmaQxnWiGKTGbr8OZIiIGVaVGC1hQUoW0V_vUlLKpN9iLqEL9IbBqipyJJBo42lI3pTCqbYla_skqmjy7BdsebGba0kIS_0nC-3OT09vevk2zZEhVZlzydL1MmEErByluC9MuX6pBAZQ-W0=w408-h306-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=%E0%B8%AA%E0%B8%B8%E0%B8%81%E0%B8%B5%E0%B9%89%E0%B8%95%E0%B8%B5%E0%B9%8B%E0%B8%99%E0%B9%89%E0%B8%AD%E0%B8%A2%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "amazon-cafe-942cdc13",
      "name": "Amazon Cafe",
      "category": "เครื่องดื่มและคาเฟ่",
      "location": "อาคารหลัก",
      "floor": "1",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=Amazon%20Cafe%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnjajj10XhYAfJASpZ3j95EqaWdZJu81FLp22noRn9uGRe8aRZfcB2iX4mAyTACiBjFeYWrUMa95z0Lq9aY-yPRJ_UOJy5-LSEjFCKjMmAALe9Cv1eUezCBYEScCWzJ5v48Xlc=w408-h306-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=Amazon%20Cafe%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "amor-e5bb0afe",
      "name": "Amor",
      "category": "ขนมและเบเกอรี",
      "location": "อาคารหลัก",
      "floor": "1",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=Amor%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkO5OOvnDbVxgZLJT8SyIjun0TuBw2ZLkkzPBOoqMliUIZOsMxl4vflJ6MfOdl_7QvhyN5SAMRYthv6GEDWa5dh4Gd9f6C21dAW1rSA6h7aR6U5K34O4v3iebvsCwsW_Xaof2TxPg=w408-h306-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=Amor%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "bonchon-f61af498",
      "name": "BonChon",
      "category": "อาหารจานด่วนและตะวันตก",
      "location": "อาคารหลัก",
      "floor": "1",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=BonChon%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnMyvx70YVKow-9YENFtUWgfo3chsG2ImR2kVXBfx_tfgdZXrdds0LeInwamtgs5avnwdaTOLTtKQuve-bjfeMEgiBMgZw-l2xoCJm80otJrL3eC0KKpRprbR-EtKx6VElXUCyi=w408-h292-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=BonChon%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "chagee-seacon-bangkae-7039b005",
      "name": "CHAGEE Seacon Bangkae",
      "category": "เครื่องดื่มและคาเฟ่",
      "location": "อาคารหลัก",
      "floor": "1",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=CHAGEE%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkYnI2TdmowgZQlvmpqH3rm_0K1EWtPs3Ex0J-pGM6acwXuY1YSZNGKiSLkJV03ne3596EV5xVDKAa_v58S2MwczYuVOaCxYrrhhaCCpcLq0YEDJMq8J8_gXk0EHld0wdSucRjfXbzcC2so=w408-h306-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.lemon8-app.com/@seaconplus_bangkae/7602836162918515201?region=th",
      "notes": "Official Seacon Plus 2026 update names this branch on floor 1; Maps needs-review; checked 2026-09-21. User-verified correction: HI TEA EVERYDAY was a duplicate of this branch."
    },
    {
      "id": "hey-coffee-a0f6359f",
      "name": "HEY! Coffee",
      "category": "เครื่องดื่มและคาเฟ่",
      "location": "อาคารหลัก",
      "floor": "1",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=HEY!%20Coffee%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWn-FqDps3WsAXvHkSFCUV5YXV593SkHfQz6g7IFnUCteZWpqGrSUSk1Dnl8F-LugFAUZsGr_SoakLX2myxUszCCSsqsw79CnyTNDS9OOAiQ5Q5AFKS108KXTWdmgzdXnAt3ZM8N9IWBs1iR=w408-h306-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=HEY!%20Coffee%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "kfc-9c23dd19",
      "name": "KFC",
      "category": "อาหารจานด่วนและตะวันตก",
      "location": "อาคารหลัก",
      "floor": "1",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=KFC%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlsFw-Yz1I5BOgNU4AFj9hhyAObZhx3TjcA16aM1LcUWgfwQdHRL3NPlhCe6jcOtZzy9oYq8n-K23UC06Hd92ccjw6H1PuOaXA0LzyHzAAooQR7AllUdu7FNtjgBhznWunJsH3FY9MjJO5E=w408-h306-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=KFC%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "koi-the-fe9635e7",
      "name": "KOI the",
      "category": "เครื่องดื่มและคาเฟ่",
      "location": "อาคารหลัก",
      "floor": "1",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=KOI%20the%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkK02GHdrkLDU-cTgGP99Q5AD6LGU2nCvYXSguPc6ewUP_hpLz-n3Nl82hf1shHVsNJ1YGyzoi42Vglf3bKDDaoJW9Gf0G2brUt-qwbAzpX7uHMOYlU5ifhLZ7DuDMBafhzqEMU=w152-h86-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=KOI%20the%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "mcdonald-s-3e351d45",
      "name": "McDonald's",
      "category": "อาหารจานด่วนและตะวันตก",
      "location": "อาคารหลัก",
      "floor": "1",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=McDonald's%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnaCCcS-HYpSYC9Ej5IfSHfcozjDq5fyBQwVCFrd_POUh3V15yY9-agZZzktP_b-M6v0FAs_WVZ2l-YwDpTKHswkxK7CtWrKOTZKjGvgFa5toEkNMu4MfYCRguXU_llJhbgSsiXVLPYEaw=w408-h306-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=McDonald's%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "mixue-35a892a2",
      "name": "MIXUE",
      "category": "เครื่องดื่มและคาเฟ่",
      "location": "อาคารหลัก",
      "floor": "1",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=MIXUE%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkBbUWC2rvlYRaEhdATX2Bsao3Rd8cAnbmvjWqRPJaa9i328PWHdqcnGsMMyJC8JqJFOz5h1TA1KPFhWxljC3iNNOYszcHvK0fvM8YMfeORis92pGNQ262FKf-6fh3ibB-tKfBKIjBV1VUZ=w408-h544-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=MIXUE%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "molto-premium-gelato-1eb88431",
      "name": "Molto Premium Gelato",
      "category": "ขนมและเบเกอรี",
      "location": "อาคารหลัก",
      "floor": "1",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=Molto%20Premium%20Gelato%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmB0czN5NVlk2VlQ6-siS3XfL0nF5WJ2xGdhTsh09ALGJUUqgtTP5jjwMNurPNz0Rz5QYZSSZUSZO-ZpCeQWNp6IjVr2TFwRwF9q-sgTPo66XHYQ_R10nGJK34TsGBzuV5ceYNV=w152-h86-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=Molto%20Premium%20Gelato%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "mr-jolly-cd0bab12",
      "name": "Mr.Jolly",
      "category": "เครื่องดื่มและคาเฟ่",
      "location": "อาคารหลัก",
      "floor": "1",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=Mr.Jolly%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnl9x7q6Z5u8zxJ7TS_o6pu-4-kTyAD7X20ldiDl2lqD2xtKyWibsv8qg-aOwReUz8huRFhTem5i6xuPKHGWb4WYoXLW5bXicJZgRxUsRDaxqpm7cTUvaxoW-I1E29mmUmsj299=w408-h544-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=Mr.Jolly%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "myeongryun-jinsa-galbi-dbd21b94",
      "name": "Myeongryun Jinsa Galbi",
      "category": "ปิ้งย่างและเนื้อ",
      "location": "อาคารหลัก",
      "floor": "1",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=Myeongryun%20Jinsa%20Galbi%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkKo-Ufc23mOhu42sY5YwARQe7NAvxkMqt-nGZT-RqelRtkO-og5EvVyKgYgzo56p1WIOAO5CFmBA29ZOLqiMS4xry9S3ULufmTwsM6eB_Ui0tIaUCmMV9ElsAxZ4ohYY8J5J_kvD5fa3eH=w408-h306-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=Myeongryun%20Jinsa%20Galbi%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "naisnow-fba21bd5",
      "name": "NAISNOW",
      "category": "เครื่องดื่มและคาเฟ่",
      "location": "อาคารหลัก",
      "floor": "1",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=NAISNOW%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWl513SLBhmxp1aPraoGxkKIIEu0oXib02ABEwf-3NSlUSN25B0B9A3tlZgODBrN6syRIzesf34e0GpOlCDHjAQQiW-A4QI5KdK6MEn2sqFClVBTaZ8rEql6yHTS2PX0xbhXOb9divkwAhQ=w408-h306-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.lemon8-app.com/@seaconplus_bangkae/7602836162918515201?region=th",
      "notes": "Official Seacon Plus 2026 update names this branch on floor 1; Maps active; checked 2026-09-21."
    },
    {
      "id": "o-li-no-c3ba79fc",
      "name": "O-li-no",
      "category": "เครื่องดื่มและคาเฟ่",
      "location": "อาคารหลัก",
      "floor": "1",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=O-li-no%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkeHasQf3rCDYCtLOH-mdrvSuanbveFutWyrEDkP-6GyQKzh7dXPLBNZ8EWqYbDcJJ0RMqP8jq_B8qnPOmcNzCMMSH42b2FK3oJPlk854b43w5gi38Th4L8ZedIIl_zV73-WZ6VeAHPvXQY=w191-h86-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=O-li-no%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "richess-2f550f05",
      "name": "Richess",
      "category": "เครื่องดื่มและคาเฟ่",
      "location": "อาคารหลัก",
      "floor": "1",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=Richess%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmAoqdyfC3VxxW6sWMdIdTOvXnNwqstv8rlLSeTpNcsleYzLNfnGSYJ9RPZwdiwxiqujvwUvdWK4DF8MGnKY_XnMaKLZNWHVumy3gwwwQNv_hlb2YKYv1Qbb6be26EcE4jfSme2=w181-h86-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=Richess%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "rowie-s-coffee-6ff5d3df",
      "name": "Rowie’s Coffee",
      "category": "เครื่องดื่มและคาเฟ่",
      "location": "อาคารหลัก",
      "floor": "1",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=Rowie%E2%80%99s%20Coffee%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmG9z69IHKEXL0OOhB3lewzqfbNpsqW1OSRV-u0ppnQm0tTJXG8fZoL5KI9AgsV8CC7KXvft_QBqIUfpTSwxYFlxGCEN75dh-3lJvW654xbihWeumNjzWUv_3qYkigd6YtqT2itsQ=w122-h92-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.lemon8-app.com/@seaconplus_bangkae/7602836162918515201?region=th",
      "notes": "Official Seacon Plus 2026 update names this branch on floor 1; Maps active; checked 2026-09-21."
    },
    {
      "id": "starbucks-64f7d01b",
      "name": "Starbucks",
      "category": "เครื่องดื่มและคาเฟ่",
      "location": "อาคารหลัก",
      "floor": "1",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=Starbucks%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkwKoHd9DTLZMhZgrmGSABW_CC0Srs0-jbbLCINL0eSWtEh_w_4ShmYuK4YQV9_LM8SOkKCa_AEBNO8_Pm-QgUWb1U_0gD1Y1zVZcbWepgy80iMZDVsXU6DNY0xUehtf4yI6sRVBQ=w408-h292-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=Starbucks%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "swensen-s-63e3539c",
      "name": "Swensen's",
      "category": "ขนมและเบเกอรี",
      "location": "อาคารหลัก",
      "floor": "1",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=Swensen's%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmYzS3Vr6UFJjvgO1E5D5ORyrJaxQJ7_ntrWcL2Dyemzp4lQlwWlb4L7xuIgm1SdcUnOj5SO5_g5X-AfchgR4tbwrx2XKJpSWk_XhFA-FXmE8DZAsOp5zoZ0CF7TfOihbE3ItNH=w408-h306-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=Swensen's%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "the-pizza-company-1984a548",
      "name": "The PIZZA Company",
      "category": "อาหารจานด่วนและตะวันตก",
      "location": "อาคารหลัก",
      "floor": "1",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=The%20PIZZA%20Company%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/grass-cs/ACvplmMYrP0CE28tmKlpw0b_MN3Pibyoh9atfe2HnPikJaZedPtywjooNHJIl6DUgKurT3-UrCIfplDfYGleGhq2JjHYCVvqXaVrEKG87wtizNtkWbE8ZA-uMWyKyab3HB9IRUeAUJk=w408-h306-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=The%20PIZZA%20Company%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "bearhouse-c547e496",
      "name": "BEARHOUSE",
      "category": "เครื่องดื่มและคาเฟ่",
      "location": "อาคารหลัก",
      "floor": "2",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=BEARHOUSE%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWldNEJ80GIukUUHUGWeE1U4hKXtYvV6Xod0QNQnKvhMZ6t92NjqAlakTIF4gphQrxA18QveSTTw4N98kxVysZOgcngTjYgORy7vN6SSHAxU4F_RUTtZFee0jUqSY0xiHdGMSso5t0uSx3YC=w408-h544-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=BEARHOUSE%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "eat-am-are-c99eab5d",
      "name": "Eat Am Are",
      "category": "อาหารจานด่วนและตะวันตก",
      "location": "อาคารหลัก",
      "floor": "2",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=Eat%20Am%20Are%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkjOaC7HmHFKCzCtTR_pQHcnNS8SPHm73VQy7SUmOo1N-fxEpjeo6KOmis2P4DB-dspPFe5ogdSf49_YaB3X0ZoKpFDYP6gNn5PSaVIP4bKIo3zI8CrWZ03O52YodBlmC2AtyyX2g=w408-h306-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=Eat%20Am%20Are%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "fuku-matcha-41ecc98a",
      "name": "FUKU MATCHA",
      "category": "เครื่องดื่มและคาเฟ่",
      "location": "อาคารหลัก",
      "floor": "2",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=FUKU%20MATCHA%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmy0qmnm7WfUhb5VOYzab3i4esbNQKhBRN8qK6raRM1c9BbfKqTkPFQcRayMFetFyjszGzGJqjTLEJN9KWd0eQFqHDIXWxerffaJ71VrziExZ1jB05KG47Ph6qldn1evjhr1Bz1fQ=w408-h306-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=FUKU%20MATCHA%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "mini-oriental-speedbar-fa7f88a6",
      "name": "Mini Oriental Speedbar",
      "category": "เครื่องดื่มและคาเฟ่",
      "location": "อาคารหลัก",
      "floor": "2",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=Mini%20Oriental%20Speedbar%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkh5RTvxWWVAZHg2T5iHEDq0L0VDkyfSH25vQYitLJyHB5WgIJ2FBLKOW0Oq8FmAHYVwSUYFHxPlDLiA9FTAcfJn94ECLTlHj4cVsgm7Gqmw_Y4tAAY4hDGnG4389YHLcGqVpKMCg=w408-h271-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.lemon8-app.com/@seaconplus_bangkae/7602836162918515201?region=th",
      "notes": "Official Seacon Plus 2026 update names this branch on floor 2; Maps active; checked 2026-09-21."
    },
    {
      "id": "inthanin-ec827568",
      "name": "Inthanin",
      "category": "เครื่องดื่มและคาเฟ่",
      "location": "อาคารหลัก",
      "floor": "3",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=Inthanin%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWm2-2xLN1hFXh7e7sKXOHpzDlitotzg25CyithySYMwaveY2jSBdsYpSrD_2LqApCo16TTTkccrmmHqzKhdyES2InhQ1vadRDuHEDNmnOvFhm7rzLmN80TLOaWSaMXVIzR3Rv-0=w408-h725-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=Inthanin%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "kita-tea-stand-9ecb35cd",
      "name": "Kita Tea Stand",
      "category": "เครื่องดื่มและคาเฟ่",
      "location": "อาคารหลัก",
      "floor": "3",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=Kita%20Tea%20Stand%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlFRfq-I3wzfBDfEBjGguNd29X-qj9UtdkmCXpVgiBkTDROHGsFJuxVWGPPMjJOqhCIledFU291h2nj4ojv-FMFwdoVDhc_sxfn1zA_vo9gMPM-MhKv6NniKo8uFh54KVlT3KuCXw=w408-h544-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=Kita%20Tea%20Stand%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "shop-51a15444",
      "name": "ข้าน้อยขอชาบู",
      "category": "เครื่องดื่มและคาเฟ่",
      "location": "อาคารหลัก",
      "floor": "4",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=%E0%B8%82%E0%B9%89%E0%B8%B2%E0%B8%99%E0%B9%89%E0%B8%AD%E0%B8%A2%E0%B8%82%E0%B8%AD%E0%B8%8A%E0%B8%B2%E0%B8%9A%E0%B8%B9%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk7kM-XaHaj6zoF4JanfJ3tNaRdBe3lzbxfPq-cJuk5lmj1pGoXGLNfB-Ttb5gZCQsrYum1XO0XqYblSZRjq7Ysm3KYo6q7HxFslAt7jB4knfcD76DnYfV1dYy9XZL9jVZI34iK8Dej6bfF=w408-h306-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=%E0%B8%82%E0%B9%89%E0%B8%B2%E0%B8%99%E0%B9%89%E0%B8%AD%E0%B8%A2%E0%B8%82%E0%B8%AD%E0%B8%8A%E0%B8%B2%E0%B8%9A%E0%B8%B9%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "shop-f9ec40dc",
      "name": "ตำตำ",
      "category": "อาหารไทยและนานาชาติ",
      "location": "อาคารหลัก",
      "floor": "4",
      "status": "active",
      "details_url": "https://www.wongnai.com/restaurants/146789IE-%E0%B8%95%E0%B8%B3%E0%B8%95%E0%B8%B3-%E0%B8%8B%E0%B8%B5%E0%B8%84%E0%B8%AD%E0%B8%99-%E0%B8%9A%E0%B8%B2%E0%B8%87%E0%B9%81%E0%B8%84",
      "image_url": "https://thanakritdacontact-tech.github.io/seacon-bangkae-food-picker/assets/tamtam-wongnai.jpg",
      "image_source": "review",
      "reference_url": "https://www.wongnai.com/restaurants/146789IE-%E0%B8%95%E0%B8%B3%E0%B8%95%E0%B8%B3-%E0%B8%8B%E0%B8%B5%E0%B8%84%E0%B8%AD%E0%B8%99-%E0%B8%9A%E0%B8%B2%E0%B8%87%E0%B9%81%E0%B8%84",
      "notes": "User-provided Wongnai branch page confirms Seacon Bangkae floor 4; local card image copied from that page because its image host blocks hotlinking; updated 2026-09-21."
    },
    {
      "id": "shop-f436bf08",
      "name": "เพลินพุง",
      "category": "อาหารไทยและนานาชาติ",
      "location": "อาคารหลัก",
      "floor": "4",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=%E0%B9%80%E0%B8%9E%E0%B8%A5%E0%B8%B4%E0%B8%99%E0%B8%9E%E0%B8%B8%E0%B8%87%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkg87_DVhUK_Dnj-N1yLOBICwkF_oVYgSdRnMl6DjEB8hwrIfJJxqhQ4D9ORz-C0yxmk4lDjkldFJJFvFsZryX8OZO7TwErrrB-3K02hsQi44i-U-zmJaxOt0sQvMwPEpxqUObdag=w408-h306-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=%E0%B9%80%E0%B8%9E%E0%B8%A5%E0%B8%B4%E0%B8%99%E0%B8%9E%E0%B8%B8%E0%B8%87%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "shop-0c04b738",
      "name": "สุกี้นางพญา",
      "category": "ชาบูและสุกี้",
      "location": "อาคารหลัก",
      "floor": "4",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=%E0%B8%AA%E0%B8%B8%E0%B8%81%E0%B8%B5%E0%B9%89%E0%B8%99%E0%B8%B2%E0%B8%87%E0%B8%9E%E0%B8%8D%E0%B8%B2%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWn30k7cVWTbbEbiUR_amob3pX-TH_qKcNKcRvDOEWIQhckR5chkSn2PirJwB2XD4SZ9en9kvovtv6oq2MI2wczvuacFgwU-5Idv494kGcrBiWfekWnf2tm8TRWIHNFe2UlN3xV6ybNbyMor=w408-h306-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=%E0%B8%AA%E0%B8%B8%E0%B8%81%E0%B8%B5%E0%B9%89%E0%B8%99%E0%B8%B2%E0%B8%87%E0%B8%9E%E0%B8%8D%E0%B8%B2%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "cafe-d2ff1169",
      "name": "หนองโพ Cafe",
      "category": "เครื่องดื่มและคาเฟ่",
      "location": "อาคารหลัก",
      "floor": "4",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=%E0%B8%AB%E0%B8%99%E0%B8%AD%E0%B8%87%E0%B9%82%E0%B8%9E%20Cafe%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/grass-cs/ACvplmOMh02OcSzwd9QcDWjoYM3I9R6CgJcpWcfrSQl2uHa73WwMPu8Br_UrQwkdzTzpe9TNEttqeT-pEZL4yXczskxl9WJC2lu71qaxSHUvPWMSBAcrFaEo9uH75rubZgciKmst-TEhLpXenHop=w408-h306-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=%E0%B8%AB%E0%B8%99%E0%B8%AD%E0%B8%87%E0%B9%82%E0%B8%9E%20Cafe%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "shop-fdb2663f",
      "name": "เหม็งแซ็ปนัว",
      "category": "อาหารไทยและนานาชาติ",
      "location": "อาคารหลัก",
      "floor": "4",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=%E0%B9%80%E0%B8%AB%E0%B8%A1%E0%B9%87%E0%B8%87%E0%B9%81%E0%B8%8B%E0%B9%87%E0%B8%9B%E0%B8%99%E0%B8%B1%E0%B8%A7%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkiH5xLuWIdeq2vtXO7-pILE0oFg7eC9nUhS3FIIHiSIZKCmAZQjIjP4zKdXc0UrpkD1_jCsxfLfPzAXyBEzBwKcC74wOndLmxSAxLafqqbbZY3ne7y65Tcl1B2E52d-rQwarM6=w122-h92-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=%E0%B9%80%E0%B8%AB%E0%B8%A1%E0%B9%87%E0%B8%87%E0%B9%81%E0%B8%8B%E0%B9%87%E0%B8%9B%E0%B8%99%E0%B8%B1%E0%B8%A7%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "shop-df0c119f",
      "name": "ฮะจิบัง ราเมน",
      "category": "อาหารญี่ปุ่น",
      "location": "อาคารหลัก",
      "floor": "4",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=%E0%B8%AE%E0%B8%B0%E0%B8%88%E0%B8%B4%E0%B8%9A%E0%B8%B1%E0%B8%87%20%E0%B8%A3%E0%B8%B2%E0%B9%80%E0%B8%A1%E0%B8%99%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnSqe-s5w1oOsHzDnaKqBt8lkta6Qp_nAofyJSDKBRQSsyklpS15jDhh8c3DBnVBQEosk7ecuRzkK9Xqd2EORzC9ima10rPIz9Yk-CToTIYK8i7C0__40sB_Z-UfejNufNhjp9A=w152-h86-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=%E0%B8%AE%E0%B8%B0%E0%B8%88%E0%B8%B4%E0%B8%9A%E0%B8%B1%E0%B8%87%20%E0%B8%A3%E0%B8%B2%E0%B9%80%E0%B8%A1%E0%B8%99%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "bake-a-wish-97bfbf5d",
      "name": "Bake a Wish",
      "category": "ขนมและเบเกอรี",
      "location": "อาคารหลัก",
      "floor": "4",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=Bake%20a%20Wish%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/grass-cs/ACvplmOQzefprYxud31KluWYOEZ0CcyeTUimZ5hrDitgJJ2pfoy5wACZ3uJ_I3JO3VSoEddgws5a03xpLAobsVEgE2OvwuiWkh2Iybfg-0iwEGkAFLcEi2d9bOKE1BQdy6s-VlLpX9XFZspBkpdp=w408-h589-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=Bake%20a%20Wish%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "bar-b-q-plaza-8f3bde3e",
      "name": "Bar B Q Plaza",
      "category": "ปิ้งย่างและเนื้อ",
      "location": "อาคารหลัก",
      "floor": "4",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=Bar%20B%20Q%20Plaza%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnpPsIOyS0VP9C9vhHjEeKVep3VRQsFMYss5pJxxEOtFtJRZ2lPz-AvUO47peAWDPef5_ixTi61ooz8qFAjy8d5QgVmQ5RfmyJvdGrGpcllPQwpEpunxrkSN-1mlVrPhBiT-AH2fQ=w408-h306-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=Bar%20B%20Q%20Plaza%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "boost-8422f60d",
      "name": "BOOST",
      "category": "เครื่องดื่มและคาเฟ่",
      "location": "อาคารหลัก",
      "floor": "4",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=BOOST%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/grass-cs/ACvplmP4t2RXfy_qM7KiveTsXlkF1OigZnyZc5pqvj6qP95OVN52Gz_YkaCkZKszQpOzTz9uqlVuKMjEgyoK5brat6pz67Y4rbU_sSRhEo2G17eHDc_Dnup3gutXmFaWKPRc-EAni67JlQ=w152-h86-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=BOOST%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "dookki-540281d1",
      "name": "DOOKKI",
      "category": "อาหารเกาหลี",
      "location": "อาคารหลัก",
      "floor": "4",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=DOOKKI%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk2zzsTIOs103K8IFtJLFr-R5t61qlGV--tFSdrkWJrmoUNpOtrLQCPCWwCbx2TJfbTw-m750PtjbyinC9XTaPeNieDfBJL5Ans49i9IfChOV7-cCBYSbblbuJX1RGzwK0c_zyHycboWm8=w408-h306-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=DOOKKI%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "gold-curry-bangkok-2910aa11",
      "name": "Gold Curry Bangkok",
      "category": "อาหารญี่ปุ่น",
      "location": "อาคารหลัก",
      "floor": "4",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=Gold%20Curry%20Bangkok%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnzv84v2H6-Rf7KwH-tLL-b9qC0CbR5y-LFBTypuvjsP9GmZLiH2EUOh5Bk2l_QZMlxLIwJ8oCIxTZFkVH-rY0J-eANh4qx1cw8vt38-6KmRlhsfN9QDIJDQdtPTGUbQxOY0GA=w408-h306-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=Gold%20Curry%20Bangkok%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "heng-cha-29584dd1",
      "name": "HENG CHA",
      "category": "เครื่องดื่มและคาเฟ่",
      "location": "อาคารหลัก",
      "floor": "4",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=HENG%20CHA%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkrFco3DiaTGC_PnzechOdueHG8u02IDrzEcLBLyOb5Hbvj61S_GkVG-kF58C3-Rcrql2EgGfzGsISNX8sDcMVVOxvyON96fySZaU5FAzFt4mrdIKTeWq5oznZd4t5JGwLk9esK=w152-h86-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=HENG%20CHA%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "mandarin-0ce37328",
      "name": "MANDARIN",
      "category": "ชาบูและสุกี้",
      "location": "อาคารหลัก",
      "floor": "4",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=MANDARIN%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmxfiyqlbRz_dXGed9_M8vaaX8FcH6tDRvuQldjcu_LqlAbaj9u-aaouxf3qqyl7kZywuJNB2RmKq1gZb6fjH188gputNch_jotUhbebCreStmolKZlMof_JsjbDNQpi74TM-qlBraSpvm8=w408-h306-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=MANDARIN%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "mk-ab66fe4b",
      "name": "MK",
      "category": "ชาบูและสุกี้",
      "location": "อาคารหลัก",
      "floor": "4",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=MK%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/grass-cs/ACvplmPO-EcU0uD8IbejAncCcWAFPU6fO-O12s44WJi-qZ770qp2KELgE67LZA2Ihn-IruRxuUEHdFxrcx0se7xEPrOsxVP21-9iYRvcZTux3fiXyA2hck6MNhLgBnqhXtGY1GehM9dlgl-sx5U=w408-h306-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=MK%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "neo-suki-0ef012b2",
      "name": "NEO Suki",
      "category": "ชาบูและสุกี้",
      "location": "อาคารหลัก",
      "floor": "4",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=NEO%20Suki%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmCCBqHnrSC20RdBg-7XACOWhMpd1aypT7vZsOhNUBxJj_8pMLUFuEMSC5BhMAqX76pBA--l2KNXovinC_iMzjtXaGYUr4wWmPkaDvwWojq06IzIE2vmCokWOmeaky4fauJxXFSjwU14hE=w408-h544-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=NEO%20Suki%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "oishi-bbe2da30",
      "name": "OISHI",
      "category": "อาหารญี่ปุ่น",
      "location": "อาคารหลัก",
      "floor": "4",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=OISHI%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlByRJ2aV8qspDZDnoyjPW6HKCBs6v4hJciCxhrUZuMup8SaVPhOop9JxSVwYlJN-sN1Pn2yg7X1jVl5XUN66_NyV3qxelICsFotxT8ZJC-71-OsfwXfkVlu-cCAop_Ap9u9GIM-Ktgq_8=w408-h306-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=OISHI%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "oishi-ramen-0d3fe7c1",
      "name": "OISHI RAMEN",
      "category": "อาหารญี่ปุ่น",
      "location": "อาคารหลัก",
      "floor": "4",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=OISHI%20RAMEN%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlByRJ2aV8qspDZDnoyjPW6HKCBs6v4hJciCxhrUZuMup8SaVPhOop9JxSVwYlJN-sN1Pn2yg7X1jVl5XUN66_NyV3qxelICsFotxT8ZJC-71-OsfwXfkVlu-cCAop_Ap9u9GIM-Ktgq_8=w122-h92-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=OISHI%20RAMEN%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "shabu-shi-1740533a",
      "name": "Shabu Shi",
      "category": "ชาบูและสุกี้",
      "location": "อาคารหลัก",
      "floor": "4",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=Shabu%20Shi%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnE8w9LYoYab5ZruiFtnEnfCvDkDW5-DHL55cr7hR-WlUDUPzXyrks8rqIAINsF7Xo0cBEwy2mLur9msmwVTGJx1fe0N_RSoWUrGoxMYj4lMyNF0Bnkfuagy7ZDYcg-G9ro98izG8tBQTEJ=w152-h86-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=Shabu%20Shi%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "sizzler-63f0a091",
      "name": "Sizzler",
      "category": "อาหารจานด่วนและตะวันตก",
      "location": "อาคารหลัก",
      "floor": "4",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=Sizzler%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmM7MNwCdsnaWjJe4873oVP69G2dG-Cq3lYA3xowndvtcey73jRBDR-2CIib0RN0lZDwnXO41yL7eyfzB-MYdLyQT19ijpX58s6hOL6poa1znSj9whNatHdzO7ROkTUysf6cY_q_Q5A6NE=w408-h306-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=Sizzler%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "sukishi-67acda61",
      "name": "Sukishi",
      "category": "ชาบูและสุกี้",
      "location": "อาคารหลัก",
      "floor": "4",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=Sukishi%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmEM23PncTUwmTPr6rBDbz33pVHiDlf-Cur0hedJ_iqyhruujLJrJ5ruI8DEyzUB4O5d2SuoaogMxf4tcU9f2BMmy5ud5HQjG4cX8w3pKF7X2upLod7kUykWm059ssvfHOhRWgou_cm2LQl=w122-h92-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=Sukishi%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "sukiya-3e735ef8",
      "name": "SUKIYA",
      "category": "อาหารญี่ปุ่น",
      "location": "อาคารหลัก",
      "floor": "4",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=SUKIYA%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/grass-cs/ACvplmPxOR9hqjyB9DEy5y8svYLqE_NvP0_flz3QpXZQoY_AW-YPbAT9fYKl6iH5jOsvfYywx4njs4x_G_vuOhLvVA832wHGHp3sURta3QmNZXZK5f6L236H9iIoK8zkFaLooy4qf7oA=w408-h261-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=SUKIYA%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "sushi-express-4dad91ab",
      "name": "SUSHI EXPRESS",
      "category": "อาหารญี่ปุ่น",
      "location": "อาคารหลัก",
      "floor": "4",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=SUSHI%20EXPRESS%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnqymSY40iCIi8U22j0pHncHwTI-8t3e0UTyR5cM7Lsh9vEUDFCKCinr72r-XJ7TuDP_AZIiTY2WTl99kL6lIDCAlH72b_npxH3DoAotrMTl6wHZBpiNrFDfRoglHBsMPBycsc56yx2D-A=w408-h306-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=SUSHI%20EXPRESS%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "sushi-plus-be3e39d4",
      "name": "SUSHi PLUS",
      "category": "อาหารญี่ปุ่น",
      "location": "อาคารหลัก",
      "floor": "4",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=SUSHi%20PLUS%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/grass-cs/ACvplmNyHeNpolRkDzXw8lav1trtCpaj9wmqY2Ops95BF7shsUpFF-iIcUWebySKhORiYHv6D6fi8rfUQ5XWJL6n5HbLKEPvxaHOZIR0sNzFcTm3XShG0PTjwAHhWaHFEyNUi4KvLWfuBYXfYrA=w408-h306-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.lemon8-app.com/@seaconplus_bangkae/7602836162918515201?region=th",
      "notes": "Official Seacon Plus 2026 update names this branch on floor 4; Maps active; checked 2026-09-21."
    },
    {
      "id": "sushiro-7d0d31c3",
      "name": "SUSHIRO",
      "category": "อาหารญี่ปุ่น",
      "location": "อาคารหลัก",
      "floor": "4",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=SUSHIRO%20Seacon%20Bangkae",
      "image_url": "https://seaconbangkae.com/Files/1stpage_JJ%20Folder/shop%20by%20brand/S_sushiroLogo.jpg",
      "image_source": "official",
      "reference_url": "https://seaconbangkae.com/shop/7",
      "notes": "Current official mall directory lists this branch on floor 4; Maps active; checked 2026-09-21."
    },
    {
      "id": "yayoi-7bbf836b",
      "name": "Yayoi",
      "category": "อาหารญี่ปุ่น",
      "location": "อาคารหลัก",
      "floor": "4",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=Yayoi%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkDdJcVbThBCCpL1kA6S6hJn_hm4yRG7LRt_18lUrE6egxbosPXOoyV6BYSgkXSh_qQLr6yp9ZiyuMd7BEm7vdnYYz404VJbLZhTURaOotirTmVnoAuab8bF-EGzlVoq8I-X-qQAA=w408-h306-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=Yayoi%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "yodcha-681ff5a5",
      "name": "YODCHA",
      "category": "เครื่องดื่มและคาเฟ่",
      "location": "อาคารหลัก",
      "floor": "4",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=YODCHA%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWktgQXG2F_0jK6iZvtXWzEKvJ_d6mKYBEsNyyHxZSGh9RNSJDxkXcPmprGgCV4JTJyQcK4ET9XpWtn3IqKzVgtSjMVvDGKK2gjfcMK0YcEBwYtYpuEO3k7IvTfXWFgtCDKpWyZE=w408-h543-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=YODCHA%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "shop-042063ec",
      "name": "ก๋วยเตี๋ยวเรือพระนคร อนุสาวรีย์ชัย",
      "category": "อาหารไทยและนานาชาติ",
      "location": "ชั้นใต้ดิน",
      "floor": "B",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=%E0%B8%81%E0%B9%8B%E0%B8%A7%E0%B8%A2%E0%B9%80%E0%B8%95%E0%B8%B5%E0%B9%8B%E0%B8%A2%E0%B8%A7%E0%B9%80%E0%B8%A3%E0%B8%B7%E0%B8%AD%E0%B8%9E%E0%B8%A3%E0%B8%B0%E0%B8%99%E0%B8%84%E0%B8%A3%20%E0%B8%AD%E0%B8%99%E0%B8%B8%E0%B8%AA%E0%B8%B2%E0%B8%A7%E0%B8%A3%E0%B8%B5%E0%B8%A2%E0%B9%8C%E0%B8%8A%E0%B8%B1%E0%B8%A2%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkT58nGZwDXMNd1XRmr8x7dycOBTFnX2vSEmQ1jEB7tKNqHBND_mDh_aXdET92NTHIcNSOaj50YitvInKNJXg1tb1B4PQAqs3TfLsxBU1l9iazdrqhMzawvkB0nww5VxNYHBf0feQ=w122-h92-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=%E0%B8%81%E0%B9%8B%E0%B8%A7%E0%B8%A2%E0%B9%80%E0%B8%95%E0%B8%B5%E0%B9%8B%E0%B8%A2%E0%B8%A7%E0%B9%80%E0%B8%A3%E0%B8%B7%E0%B8%AD%E0%B8%9E%E0%B8%A3%E0%B8%B0%E0%B8%99%E0%B8%84%E0%B8%A3%20%E0%B8%AD%E0%B8%99%E0%B8%B8%E0%B8%AA%E0%B8%B2%E0%B8%A7%E0%B8%A3%E0%B8%B5%E0%B8%A2%E0%B9%8C%E0%B8%8A%E0%B8%B1%E0%B8%A2%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "shop-5eb6e833",
      "name": "ไข่หวานบ้านซูชิ",
      "category": "อาหารญี่ปุ่น",
      "location": "ชั้นใต้ดิน",
      "floor": "B",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=%E0%B9%84%E0%B8%82%E0%B9%88%E0%B8%AB%E0%B8%A7%E0%B8%B2%E0%B8%99%E0%B8%9A%E0%B9%89%E0%B8%B2%E0%B8%99%E0%B8%8B%E0%B8%B9%E0%B8%8A%E0%B8%B4%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk1-yKumCYrPpueJHvd8iR7huTf5omdTKjCQQbq3QeBfXZolCGzN1HZ4IfTY3wltuIlvhPruEE-0UpipX_cr67rAfhgBKWpjGv45ZMZzUlCROpKVMQ3ZN6YGMIi5qzdYTI4R13v0g=w408-h306-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=%E0%B9%84%E0%B8%82%E0%B9%88%E0%B8%AB%E0%B8%A7%E0%B8%B2%E0%B8%99%E0%B8%9A%E0%B9%89%E0%B8%B2%E0%B8%99%E0%B8%8B%E0%B8%B9%E0%B8%8A%E0%B8%B4%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "shop-329fab2f",
      "name": "ซาโตด้ง",
      "category": "อาหารญี่ปุ่น",
      "location": "ชั้นใต้ดิน",
      "floor": "B",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=%E0%B8%8B%E0%B8%B2%E0%B9%82%E0%B8%95%E0%B8%94%E0%B9%89%E0%B8%87%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlPZBqLMuRvS8UQsmVk12C2hWnbExYPidPVU6_VutvDaCxsqbUyXIHA1-dhrgq4GMx7GKiJXh2k0OJamSzqsCyca4s7DZ92fHX1kwhGL4O-Ot_HB-sFxCa2HRB8DSl_gavK6gh_ZzDlN5Ls=w408-h306-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=%E0%B8%8B%E0%B8%B2%E0%B9%82%E0%B8%95%E0%B8%94%E0%B9%89%E0%B8%87%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "shop-48fcc998",
      "name": "ดาหลา",
      "category": "ขนมและเบเกอรี",
      "location": "ชั้นใต้ดิน",
      "floor": "B",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=%E0%B8%94%E0%B8%B2%E0%B8%AB%E0%B8%A5%E0%B8%B2%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkKmqKoiiR4lcy2kIli8Wh_ViD710MaNxr7FABf4mT_LvCU5adSN8zPH12WX18UjIgjglsWuD1JvK2vSfl9OpsHJ-0FH8NA_J9OzsSKi0-o0jkL2KwX_nrByhVTokOxk2ufyg9Q=w408-h544-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=%E0%B8%94%E0%B8%B2%E0%B8%AB%E0%B8%A5%E0%B8%B2%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "dolce-gelatino-e544d0f5",
      "name": "โดเช่ (Dolce Gelatino)",
      "category": "อาหารไทยและนานาชาติ",
      "location": "ชั้นใต้ดิน",
      "floor": "B",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=%E0%B9%82%E0%B8%94%E0%B9%80%E0%B8%8A%E0%B9%88%20(Dolce%20Gelatino)%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlnh4UU7GctDEP9VGT7HVsBJfpUaMgDIjiro1VWYnkajuszYBqk-cE1lg8jl37rg_fH3W1HFFh_Ue_9CC5HHNZhzqLTntTe-9QAx44zMuDDXCmtsDhvKhLmkSm2qoU2ZT4PxFRf=w164-h86-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=%E0%B9%82%E0%B8%94%E0%B9%80%E0%B8%8A%E0%B9%88%20(Dolce%20Gelatino)%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "shop-bc43379e",
      "name": "เตี๋ยวบางกอก",
      "category": "อาหารไทยและนานาชาติ",
      "location": "ชั้นใต้ดิน",
      "floor": "B",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=%E0%B9%80%E0%B8%95%E0%B8%B5%E0%B9%8B%E0%B8%A2%E0%B8%A7%E0%B8%9A%E0%B8%B2%E0%B8%87%E0%B8%81%E0%B8%AD%E0%B8%81%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkra_WxTLvGk1BORnxolXTkRmp6x3duEKfc1ZQ54GKUs3BSnaIvpSdQjJODg-OyowFwXjD08X_6snJw8VJHmjPZcsbVhlwJF5XRSlmFCpnHiiTi4AohyQj5g3tixUvof1N7lLpl=w408-h306-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=%E0%B9%80%E0%B8%95%E0%B8%B5%E0%B9%8B%E0%B8%A2%E0%B8%A7%E0%B8%9A%E0%B8%B2%E0%B8%87%E0%B8%81%E0%B8%AD%E0%B8%81%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "shop-8038520e",
      "name": "หยกสด",
      "category": "ขนมและเบเกอรี",
      "location": "ชั้นใต้ดิน",
      "floor": "B",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=%E0%B8%AB%E0%B8%A2%E0%B8%81%E0%B8%AA%E0%B8%94%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmrVEHo3I0E9Z2hCFjD0vrpyd8Ua8hjSTknyIQRQpk5B-0M5qEqdxmhnk6mwKve8___INvJKpWsUhnFOl8LyF5OEUwvzZuAR_X9JECxODIxJ3YiW3cHIzQLQnMrRsGXn5yz1NE99g=w408-h544-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=%E0%B8%AB%E0%B8%A2%E0%B8%81%E0%B8%AA%E0%B8%94%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "baron-s-bar-5728de77",
      "name": "Baron's Bar",
      "category": "เครื่องดื่มและคาเฟ่",
      "location": "ชั้นใต้ดิน",
      "floor": "B",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=Baron's%20Bar%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnYnFZ5nluZe_o_1VMQs3h3cfjKm1oz7pP2hq62K_7gILxS_USwLQ8mZS7US6_KQb0toHIp2_e8__1Xwf081HLT56H6wsj9g4ab2oeBFoXL2WE9h-PFqgCuNFjuchG3eVgkU116Oor5HSw=w408-h544-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.lemon8-app.com/@seaconplus_bangkae/7602836162918515201?region=th",
      "notes": "Official Seacon Plus 2026 update names this branch on floor B; Maps active; checked 2026-09-21."
    },
    {
      "id": "bonjour-6aff5e5b",
      "name": "bonjour",
      "category": "ขนมและเบเกอรี",
      "location": "ชั้นใต้ดิน",
      "floor": "B",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=bonjour%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlyc03uHDEx8hLh8BjXj4ZiC401lUt7NbRpEYVM24wR_dEGaU_VgpacLQCexXneVxe-M3kw7WCCRnSRjWwegEsYcpFkMFLgYkl4Ml1HsGr7Z9-1U9r0R4qzTmZO-kVaiBKXBUeiIiz11gI=w408-h544-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=bonjour%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "bowcake-c7062d92",
      "name": "Bowcake",
      "category": "ขนมและเบเกอรี",
      "location": "ชั้นใต้ดิน",
      "floor": "B",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=Bowcake%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlHFYwN73_O-MjOTuoOdjgb1Y8G7lp6JLwpP5snClThvD-i1LES3E5OlD1wYM39WdWFtXiXRpMbbQR2SyuTVlMxQPRMZx0P4dqDsz9UjEP0eXEmiWQh9_LW5449kC0DQdGL_Kfy=w408-h306-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=Bowcake%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "bun-8bf9b01a",
      "name": "Bun",
      "category": "อาหารไทยและนานาชาติ",
      "location": "ชั้นใต้ดิน",
      "floor": "B",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=Bun%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/grass-cs/ACvplmO_aAmp6ka7rlrUNg1mDkdkm-Q6INvl_jqTcz3yIk9zeOQ1Qpk6d5bAau6WE9jK_pztQ6WWIQ1qaTWxHeJ0fOd-5hr-ZmiO2HPeL0r9MsI-XP-VNJoB_Up3Fmxc70iGbpvaHk6Chi5xfcI=w408-h544-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=Bun%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "dunkin-1795756a",
      "name": "Dunkin",
      "category": "อาหารไทยและนานาชาติ",
      "location": "ชั้นใต้ดิน",
      "floor": "B",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=Dunkin%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkDHVzBrfI8pMIkggqoVA7AM46-FjcPUCvV1_6xmP1_u-NSvtgQzzxgLo6wbAyn9kFbmn4JrOSc3LaT1fdd3QT-inueC8gHRqxgjt7Tzw_xLV_1lNmBSGZzr9usxt23I5ylLN62=w408-h725-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=Dunkin%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "fantuan-55251987",
      "name": "Fantuan",
      "category": "อาหารไทยและนานาชาติ",
      "location": "ชั้นใต้ดิน",
      "floor": "B",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=Fantuan%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmbeiQ3iNwGegvuo0kQpOPl_VI03mlvpFyTijCC9wxTNvT1aLN2NL_lShKaP5E1vfyiKKzNp-vV9VTzYbAqMaUjehhk_wPuhHLi5aW1strFy9bqdGgKhxfVsy9Fjm4ttVwwtIQ=w408-h544-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=Fantuan%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "fuji-067b64a2",
      "name": "Fuji",
      "category": "อาหารญี่ปุ่น",
      "location": "ชั้นใต้ดิน",
      "floor": "B",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=Fuji%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkWOPtz1Ts5JupkORpActGUAMLFn_q6ktBlZ-v_4SlmNg4QhxzCrO-Ht_QFt3H83y0kHoXgb31BMyiGnwhB0ikqPv9I9RlO0zzmBAaX37OWQRYiDOYPSaUdFT9k1J7z9NLnhZJ7tSzc5MOZ=w408-h306-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=Fuji%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "gugu-chicken-7801b555",
      "name": "GuGu Chicken",
      "category": "อาหารจานด่วนและตะวันตก",
      "location": "ชั้นใต้ดิน",
      "floor": "B",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=GuGu%20Chicken%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmKyKRcRLEECTnXo3dq5ujb9wWH28uBESgDWJBMzVnjT9WhjtY3YEI1LMDCgzXTXIvwUpUr-JYfp6qL5w3wJXYFTyHnkX7KR_a6YTr1Gb8NCgGO7cCUZhnF78vFZMppobK7cYg=w153-h86-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=GuGu%20Chicken%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "italasia-4eb1f584",
      "name": "Italasia",
      "category": "เครื่องดื่มและคาเฟ่",
      "location": "ชั้นใต้ดิน",
      "floor": "B",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=Italasia%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnsP8CoDHEpztCRC2UERu8fLWUvFIICNwRtpYfGlkB_EF1xPYoe3FTN4bYTeVtE05aDFrWfECvnvwuX3iCeAayu2b8ZZCIxHzw0Ny5UAhFdRt_NdsQcuVbm-90T0KIBGBSUL_3vuv57SYI=w408-h272-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.lemon8-app.com/@seaconplus_bangkae/7602836162918515201?region=th",
      "notes": "Official Seacon Plus 2026 update names this branch on floor B; Maps active; checked 2026-09-21."
    },
    {
      "id": "kyodai-ramen-0fbc5cbe",
      "name": "Kyodai Ramen",
      "category": "อาหารญี่ปุ่น",
      "location": "ชั้นใต้ดิน",
      "floor": "B",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=Kyodai%20Ramen%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkIC9wr6jUw2RnPHKHMwq3723cS_bhlj3dD1JPertYm_GmRpHPRZ7osp5YPUiMJ3BvvvvOAZcsJ3bb9dZmvReY7djEOxOmglimjlFzlWNpfX6hYoT45OJuhLhSO89D0HfFToa7MFQ=w122-h92-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=Kyodai%20Ramen%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "mk-2aca2501",
      "name": "MK",
      "category": "ชาบูและสุกี้",
      "location": "ชั้นใต้ดิน",
      "floor": "B",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=MK%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkqKvD-Qn9VdRvGnINsXGkkBRch0-wC7e40WXSYQMGWqibglQJx17kMb2a-wHZnUSlC5jqqJdrj03mA0y_2fbKMePE5Kiuwq2GS_hKBeNujScQMnDUzZfJka5D19nxS-RpugPQfOu-K7fU=w122-h92-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=MK%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "mungkornbin-2c871ad2",
      "name": "Mungkornbin",
      "category": "เครื่องดื่มและคาเฟ่",
      "location": "ชั้นใต้ดิน",
      "floor": "B",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=Mungkornbin%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/grass-cs/ACvplmOJOnz_o4gYzDsLj-nvL4pmJQxoUQTtSG2hcKPBnyCH-nK2OmxTY5-WSnYOVLbWkTPU26Ma_u1QKgKMWiuL7LQ3cILzjVrqn023NiwKDCzHEsLiidd-1eN4ThewE8i4DvHrfmNy90WkMj4u=w408-h306-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=Mungkornbin%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "n-b-pancake-1be54728",
      "name": "N&B Pancake",
      "category": "ขนมและเบเกอรี",
      "location": "ชั้นใต้ดิน",
      "floor": "B",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=N%26B%20Pancake%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkaEBVopnlcF4SESnutx2rGfdkbXll7PKNPXUtuOoaqYHo5bM3Fs6IhZqEUXlA8ITSkYeYc4GPi1nKTXP4n7Qji0C5voR8Kf9lxl3umHmo2Yscxk-qEc82iSu7A0sLrY6cvKJXq=w122-h92-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=N%26B%20Pancake%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "potato-corner-86f11780",
      "name": "Potato Corner",
      "category": "อาหารไทยและนานาชาติ",
      "location": "ชั้นใต้ดิน",
      "floor": "B",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=Potato%20Corner%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlZTDKd_7arz2SBZY_H4dKACRBVA_3IkdBZ1n70br5i71qPW6t-M1UUWBqsL0PMNSiAw1AlkAOXS_htf1A-cbcnaeSIxF849T5_yAqMfcRNy8n3M1-8ggnSv8Kbb1nYhXnzg8AP=w408-h306-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=Potato%20Corner%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "shangarila-947909b4",
      "name": "SHANGARILA",
      "category": "อาหารไทยและนานาชาติ",
      "location": "ชั้นใต้ดิน",
      "floor": "B",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=SHANGARILA%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkiSXHFdJ37d5m0fycGyGv_2CCd3dxFO9a6WeRw_nhcGYcgX7HqcjaxRNq4aNSdFvxiL8Yj9AdyTMAcxhbPmkZsNZd02tkpyXoe26Iuj6ig8cCszsaJgJwHZ_gSm5pPr6mYjPBOZ2NIU8g=w408-h544-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=SHANGARILA%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "shinkanzensushi-b0939d4d",
      "name": "Shinkanzensushi",
      "category": "อาหารญี่ปุ่น",
      "location": "ชั้นใต้ดิน",
      "floor": "B",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=Shinkanzensushi%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/grass-cs/ACvplmNvefxRTMMo9C9IBy50FWg6rPG9neDlTRUnjpO07vqz-c309eENH5UFEaZJhPBDS8NUA6KBt6rvAlqcWYTL0kVOCGCUD1OwBtA2HquNozYdAXqaTqCbg9pc6LVezMhxPSzWbghvlCY8YesS=w408-h306-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=Shinkanzensushi%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "s-p-bakery-mart-faebdc50",
      "name": "S&P Bakery Mart",
      "category": "ขนมและเบเกอรี",
      "location": "ชั้นใต้ดิน",
      "floor": "B",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=S%26P%20Bakery%20Mart%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWko8SG9uHisgBPbON_4TjIVwFzVnKIlSxlpD0RZ3D13g9iK29a-Mja32XSDRNdN2-kRU-91sebeWBUesKGchIB_ONbDiCsDtEH0T_VLBB-XPkL_jvOMZcUrSsgjnWhpKxt3cRXU=w140-h186-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=S%26P%20Bakery%20Mart%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "thai-organic-cafe-375b510f",
      "name": "Thai Organic Cafe",
      "category": "เครื่องดื่มและคาเฟ่",
      "location": "ชั้นใต้ดิน",
      "floor": "B",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=Thai%20Organic%20Cafe%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmKMKnU-WlIkEgJe9UHhfLOlYB8sC4sD4Qo1AUMmqKuMV10tYJjV5OMq3zYyeppK7yzSrXvNknxYP9-Se1icwhSSRTUUXtqntnq6AuYafJaJma8v6rpLnuZ5xIQD05jMZlIgjlopw=w152-h86-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=Thai%20Organic%20Cafe%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "the-black-dragon-c809bf4e",
      "name": "The Black Dragon",
      "category": "เครื่องดื่มและคาเฟ่",
      "location": "ชั้นใต้ดิน",
      "floor": "B",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=The%20Black%20Dragon%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmAiQR3yX4db3Ub8m--Yy8LgSjtzKnaLRpnEjeUrF18Tkj1ihnjTvQOGA9UdpLh5SBEIntEqZ7pm30Wz54WKQ4-erm2eN9K7VdVqGrbTUInPJL32Ri6ORncoOjxcwcbwKZYGiKx=w408-h306-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=The%20Black%20Dragon%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "wabisabi-6f776db5",
      "name": "Wabisabi",
      "category": "อาหารญี่ปุ่น",
      "location": "ชั้นใต้ดิน",
      "floor": "B",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=Wabisabi%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWn21Z4rAk5pSNBXycJk_YwaIkJr2NkXU_hyf8zUfgui1MF3J4GoZlexlrikPZuhP6xXTxIXgdB9-1lkJb8mKAdArqVLT6m9oitLGxtBIRC-iJYl2YQJ2nzuU6sN65wMzHuIit8=w408-h272-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=Wabisabi%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "white-story-69a1609c",
      "name": "White Story",
      "category": "อาหารไทยและนานาชาติ",
      "location": "ชั้นใต้ดิน",
      "floor": "B",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=White%20Story%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWm96-lGrA6poU6yo77cqY8_sNYVgsENo-NAKrowCWsWKOm5Vvf6Ka2xxzYKkBzQSgmBJy6-RM5cqbMjC5nfU6IQU519SNGlEREmFac63EBLc30rrxbtNFR5bgYhOyURoVVcNSb-ZQ=w408-h294-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=White%20Story%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "yogurtdeli-605bb66d",
      "name": "YogurtDeli",
      "category": "เครื่องดื่มและคาเฟ่",
      "location": "ชั้นใต้ดิน",
      "floor": "B",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=YogurtDeli%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnt1JqA-eJquizkgsMYdewHFKLrl38bx3qqJS3Q9eROFdnDDvQ478Oz0c2AbetEIDpAtCuonBImzL-cQn00mwz7z_YcSUUeMCKMx6h2xbRPryQqDFKnLVAiew1-YkEhY9Nk0rTwbw=w122-h92-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=YogurtDeli%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "yoguruto-65fa6ef6",
      "name": "Yoguruto",
      "category": "เครื่องดื่มและคาเฟ่",
      "location": "ชั้นใต้ดิน",
      "floor": "B",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=Yoguruto%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmSloz8jDWVV7ktRfp4vgfrpE4HrW9yWdhzr5IVXTyAcn8MwfC0PeJvpo0DsYzCCwprdMW-OgYk04iyaKoh11xj2ipN9Q18BWrV_onWfZ6qRGkyWgmgHhZOOOUbMS_Sl17mt08H9A=w408-h544-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=Yoguruto%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    },
    {
      "id": "yotori-42ef3bf0",
      "name": "Yotori",
      "category": "อาหารญี่ปุ่น",
      "location": "ชั้นใต้ดิน",
      "floor": "B",
      "status": "active",
      "details_url": "https://www.google.com/maps/search/?api=1&query=Yotori%20Seacon%20Bangkae",
      "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlQvjBX3xIvVzDvWrkklck3xIdARnJ3i5o03OSB6e3a-vlqML6jsVy8QZXe7d73q2qweJa-mrWlsuyi975gLn_4e1nlFUKgJGHTbtO2FroNM-lsc3F6Uv-IegdHhMZgmROQbdCaOnssIDuA=w215-h86-k-no",
      "image_source": "google-maps",
      "reference_url": "https://www.google.com/maps/search/?api=1&query=Yotori%20Seacon%20Bangkae",
      "notes": "Google Maps matched the Seacon Bangkae branch and displayed current hours; checked 2026-09-21."
    }
  ],
  "counts": {
    "active": 86,
    "closed": 1,
    "needs-review": 28
  }
};
